
# Site settings
title: BSides Munich 2024
subtitle: "A free security conference in the heart of Bavaria"
repository: BSidesMUC/BSidesMunich2024

url: "https://2024.bsidesmunich.org" # the base hostname & protocol for your site
baseurl: ""
cover: "/assets/cover.png"
logo: "/assets/logo.png"

# Build settings
markdown: kramdown

collections:
  talks:
    output: true
    permalink: /:collection/:title/
#    /:collection/:title/index.html
  workshops:
    output: true
    permalink: /:collection/:title/
#    permalink: /:collection/:title
  organizers:
    output: false
  sponsors:
    output: false

# Google analytics
# ga_tracking_id: "UA-XXXX-1"

imprint:
  #name: "BSides Munich, Mr. Frederic Mohr"
  name: "MUC:SEC e.V."
  addressco: "c/o LastBreach"
  address: "Rohrauerstraße 70, 81477 München"
  email: "manager [at] bsidesmunich [dot] org"
  #phone: "+49 89
  chair: Christoph Kemetmüller
  vicechair: Ana Oprea


conference:
  # contact e-mail, e.g., for sponsors
  email: organizers@bsidesmunich.org
  twitter: https://twitter.com/bsidesmunich
  discord: https://discord.gg/RVWbAk5R6u
  notice: 

  sponsors:
    contact: sponsors (at) bsidesmunich (dot) org
    #show the sponsors in the footer of every page
    lookingfor: true
    footer: false #BETA
    # sponsor logos should all have the same format (at least width)
# uncomment it to fill sponsors in

  links:
    sponsorpackage_en_uri:  /files/BSidesMunich2024Sponsorship-English.pdf
    sponsorpackage_de_uri:  # /files/BSidesMunich2024Sponsorship-Deutsch.pdf
    cfp_uri: 
    contickets_uri: 
      
  dates: 
    deadline_tickets: 
    deadline_cfp: 
    workshops: 2024-11-10
    conference: 2024-11-11
  venue:
    workshopsday:
      address: 
      details: "TBD"
      gps: 
        lat:  
        long:  
    conferenceday:
      address: Arabellastraße 6, 81925 München
      details: "The Westin Grand Munich"
      gps: 
        lat: 48.1520938
        long: 11.6149413

  archive:
    a2023:
      title: "BSides Munich 2023"
      participants: 991338
      presentations: 1338
      workshops: 1338
      hours: 1338
      website_uri: https://2023.bsidesmunich.org
      recordings_uri: https://www.youtube.com/watch?v=A0InqK78dME&list=PL8N5HiRDvZ-dVdLNXf6kC3WDi8AWBS27g
      slider:
      - src: img/slider-bg.png

compress_html:
  clippings: all
  comments: all
  ignore:
    envs: []
  blanklines: false
  profile: false

exclude:
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "Makefile"
  - "INSTALL.txt"
  - "LICENSE.md"
  - "*.gemspec"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

pre_build:
  commands:
    - export LC_ALL="C.UTF-8"
    - export LANG="en_US.UTF-8"
    - export LANGUAGE="en_US.UTF-8"

plugins:
  - "jekyll-github-metadata"